# general configuration
# baseurl: ''
url: "http://tinkershack.in"

# shack configuration
shack:
        logo: "/images/ts-small-96.png"
        author: "Tinker Shack"
        tagline: "Hoist the colours!"
        include_content: true
        include_analytics: true

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

google_analytics: UA-115878298-1

# exclude
exclude:
        - CNAME
        - Gemfile
        - Gemfile.lock
        - LICENSE
