# general configuration
url: 'tinkershack.in'
# baseurl: ''

# shack configuration
shack:
  logo: "/images/ts-small-96.png"
  author: "Tinker Shack"
  tagline: "Hoist the colours!"
  include_content: true
  include_analytics: true

google_analytics: UA-115878298-1

# exclude
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "LICENSE"]

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty
